- type: entity
  parent: MobHuman
  id: N14MobHumanVaultDweller
  name: VaultDweller
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [VaultDwellerGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanVaultDoctor
  name: VaultDoctor
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [VaultDoctorGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanVaultEngineer
  name: VaultEngineer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [VaultEngineerGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanVaultSecurity
  name: VaultSecurity
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [VaultSecurityGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanOverseer
  name: VaultOverseer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [OverseerGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

