- type: entity
  parent: MobHuman
  id: N14MobHumanTribal
  name: Tribal
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [TribalGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanTribalElder
  name: TribalElder
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [TribalElderGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanTribalFarmer
  name: TribalFarmer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [TribalFarmerGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

- type: entity
  parent: MobHuman
  id: N14MobHumanTribalHealer
  name: TribalHealer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: Loadout
      prototypes: [TribalHealerGear]
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last
    - type: NpcFactionMember
      factions:
      - NanoTrasen

